export const users = [
  {
    id: 1,
    name: "Alex Morgan",
    age: 26,
    profession: "Software Engineer",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=774&q=80",
    distance: "15 km away",
    bio: "Passionate full-stack developer with 5+ years of experience building scalable web applications. Love hiking, photography, and coffee.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "UI/UX Design",
      "Machine Learning",
      "Photography",
    ],
    education: "Stanford University",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    experience: "5+ years",
    interests: ["Hiking", "Photography", "Coffee", "Tech Talks"],
  },
  {
    id: 2,
    name: "Taylor Chen",
    age: 28,
    profession: "Product Designer",
    image:
      "https://images.unsplash.com/photo-1494790108755-2616b786d4d0?ixlib=rb-4.0.3&auto=format&fit=crop&w=774&q=80",
    distance: "8 km away",
    bio: "UI/UX designer passionate about creating beautiful and functional digital experiences. Avid reader and yoga enthusiast.",
    skills: [
      "Figma",
      "Adobe XD",
      "User Research",
      "Prototyping",
      "Illustration",
      "Yoga",
    ],
    education: "RISD",
    company: "DesignStudio",
    location: "New York, NY",
    experience: "6+ years",
    interests: ["Reading", "Yoga", "Art Galleries", "Minimalism"],
  },
  {
    id: 3,
    name: "Jordan Lee",
    age: 24,
    profession: "Data Scientist",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=774&q=80",
    distance: "22 km away",
    bio: "Data scientist with a passion for machine learning and AI. Enjoy solving complex problems and playing chess in my free time.",
    skills: [
      "Python",
      "TensorFlow",
      "Data Analysis",
      "SQL",
      "Machine Learning",
      "Chess",
    ],
    education: "MIT",
    company: "DataTech",
    location: "Boston, MA",
    experience: "3+ years",
    interests: ["Chess", "AI Research", "Podcasts", "Board Games"],
  },
  {
    id: 4,
    name: "Morgan Rivera",
    age: 29,
    profession: "DevOps Engineer",
    image:
      "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?ixlib=rb-4.0.3&auto=format&fit=crop&w=774&q=80",
    distance: "12 km away",
    bio: "Cloud infrastructure specialist who loves automating everything. Mountain biker and coffee roaster on weekends.",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux"],
    education: "UC Berkeley",
    company: "CloudSystems",
    location: "Seattle, WA",
    experience: "7+ years",
    interests: [
      "Mountain Biking",
      "Coffee Roasting",
      "Tech Blogging",
      "Open Source",
    ],
  },
];
